apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: conumser
  name: conumser-src
  namespace: conumser
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: conumser:src
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://gitea.vrutkovs.eu/vadim/conumser
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: conumser:golang1.11
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - github:
      secret: dbb3f5b90a1a1283
    type: GitHub
