kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: conumser
  namespace: conumser
spec:
  host: conumser.vrutkovs.eu
  subdomain: ''
  to:
    kind: Service
    name: conumser
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
