name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: vrutkovs/action-s2i@master
      with:
        path: .
        base: quay.io/vrutkovs/golang-s2i:golang-1.13
        image: conumser:src
    - uses: vrutkovs/action-bin-container@master
      with:
        source_image: conumser:src
        source_path: /opt/app-root/gobinary
        binary_base: registry.access.redhat.com/ubi8/ubi
        binary_path: /usr/local/bin/conumser
        binary_image: quay.io/vrutkovs/conumser:latest
    - name: login to quay
      run: docker login -u vrutkovs -p $DOCKER_PASSWORD quay.io
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      if: github.event_name == 'push'
    - name: push the image
      run: docker push quay.io/vrutkovs/conumser:latest
      if: github.event_name == 'push'
